### ISSUE TITLE
build-app.sh is missing some libraries

### ISSUE THREAD

**Issue by honyczek** [lupyuen/pinetime-rust-mynewt#15]
After running ./scripts/nrf52/build-boot.sh I executed ./scripts/build-app.sh and after some time it failed on error `Undefined main`, so I ran it again and it fails on this:

```
----- Build Rust app
+ cargo build --target thumbv7em-none-eabihf
error: failed to read `/home/pi/pinetime-rust-mynewt/rust/druid-embedded/druid/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Expected behavior: druid toolkit will be available (pre-downloaded) in the directory ~/pinetime-rust-mynewt/rust/druid-embedded.

After trying to fix it by clonning repository druid-embedded, it continues with the same error for piet-embedded, kurbo-embedded and st7735-lcd-batch-rs.

**Comment by lupyuen** [comment]
Hi: I think the sub-repos were missing because we didn't use the `--recursive` flag when running `git clone pinetime-rust-mynewt`.  Here's how we can fix that... 

```bash
cd pinetime-rust-mynewt/rust
git submodule update --init
```

**Comment by honyczek** [comment]
Ok, as you updated README.md with `--recursive` and I started from the scratch, this issue is solved.
