### ISSUE TITLE
Send bootloader version to application

### ISSUE THREAD

**Issue by endian-albin** [lupyuen/pinetime-rust-mynewt#23]
It would be useful if the application could somehow get the version of the running bootloader. This would allow

* displaying this information to the user
* different application behaviour, for example resetting the watchdog timer or not.

**Comment by lupyuen** [comment]
Sorry I'm not planning to make any more changes to MCUBoot. Do have any suggestions how this could be done?

**Comment by lupyuen** [comment]
I'll close this issue for now since I won't be making any more updates to MCUBoot. Please submit a tested PR if we need to update MCUBoot.

**Comment by endian-albin** [comment]
That's OK. No, I'm afraid that I don't have any suggestions at the moment. By the way, I resolved the second point above (in Hypnos) by checking whether a watchdog is running and, if so, start feeding it.
