### ISSUE TITLE
Build failes on Build Rust app

### ISSUE THREAD

**Issue by RamDav** [lupyuen/pinetime-rust-mynewt#39]
Hello i'm trying to build the Firmware Image via VisualStudioCode

After starting the application build process it fails with the following errors.

--- 

Building target targets/nrf52_my_sensor
Linking D:/****/pinetime-rust-mynewt/bin/targets/nrf52_my_sensor/app/apps/my_sensor_app/my_sensor_app.elf
Error: c:/program files (x86)/gnu arm embedded toolchain/10 2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: D:/****/pinetime-rust-mynewt/bin/targets/nrf52_my_sensor/app/libc/baselibc/libc_baselibc.a(start.o): in function `_start':
D:\****\pinetime-rust-mynewt/repos/apache-mynewt-core/libc/baselibc/src/start.c:39: undefined reference to `main'
collect2.exe: error: ld returned 1 exit status

Could Not Find D:\****\pinetime-rust-mynewt\target\thumbv7em-none-eabihf\debug\libapp.a
----- Build Rust app

D:\****\pinetime-rust-mynewt>cargo build --target thumbv7em-none-eabihf
   Compiling app v2.1.1 (D:\****\pinetime-rust-mynewt\rust\app)
error: proc macro panicked
   --> rust\app\src\app_network.rs:98:20
    |
98  |       let _payload = coap!( @json {        
    |  ____________________^
99  | |         //  Create `values` as an array of items under the root.
100 | |         //  Assume `val` contains `key: "t", val: 2870, geo: { lat, long }`. 
101 | |         //  Append to the `values` array the Sensor Key, Value and optional Geolocation:
...   |
107 | |         "device": &device_id,
108 | |     });
    | |______^
    |
    = help: message: index out of bounds: the len is 1 but the index is 1
    = note: this error originates in the macro `$crate::json_rep_set_text_string` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `app` due to 2 previous errors
✅ ◾ ️Done! 

--- 

I'm an experienced Embedded Softwae Developer.
I hoped to use the PineTime as starting point for complex embedded Rust applications. 
Due to this fact im rather inexperienced in programming with Rust
I tried to debug the build with the proposed solution:

--- 

 (in Nightly builds, run with -Z macro-backtrace for more info)

PS D:\***\pinetime-rust-mynewt> cargo build -Z macro-backtrace
error: unknown `-Z` flag specified: macro-backtrace

--- 

Running on Windows 10 with Visual Code.

--- 

 git log -r
commit eab7a6460957e3759b956f8a9232e17081dabd56 (HEAD -> master, origin/master, origin/HEAD)
Author: Lee Lup Yuen <luppy@appkaki.com>
Date:   Wed Apr 21 09:46:00 2021 +0800

    Update FUNDING.yml

commit 65e8519c2dc540e92ccc4ad31f3e9c4daa89c9f1
Author: Lee Lup Yuen <luppy@appkaki.com>
Date:   Sun Apr 18 18:28:33 2021 +0800

    Don't run workflow on PR

commit 158d767ec28ad5010a81fd4e50086dcc0b7a83a8
Author: lupyuen <luppy@appkaki.com>
Date:   Fri Apr 9 09:16:41 2021 +0800

    Standardise header and footer

---

**Comment by lupyuen** [comment]
Hi: Sorry I'm no longer supporting PineTime. I hope you can switch over to another PineTime OS, like InfiniTime. Thanks :-)

**Comment by RamDav** [comment]
Ok,
thanks i can totally understand that :-)
